name: Run Nempy Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [ created ]
  workflow_dispatch: # manual trigger
  
jobs:
  test:
    # Matrix testing to test across OSs and Python versions
    # Fail-fast: fail the entire job as soon as anything fails
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
      # Necessary for poetry & Windows
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Sync dependencies
        run: uv sync

      - name: Run tests
        run: uv run --frozen pytest tests src -ra --doctest-modules
          
  publish:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: test
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/nempy/
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      # Install uv with cache
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      # Sync dependencies
      - name: Sync dependencies
        run: uv sync
      # Build
      - name: Build
        run: uv build
      # Publish to PyPI
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

